  version: '3.7'
services:
  app:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - QUOTE_STORE_SERVICE_HOST=redis
    ports:
      - "8000:8000"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
