apiVersion: v1
kind: Service
metadata:
  name: quote-store
  labels:
    app: quote-api
    role: persistent-storage
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: quote-api
    role: persistent-storage
