apiVersion: v1
kind: Service
metadata:
  name: quote-frontend
  labels:
    app: quote-api
    role: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: quote-api
    role: frontend
